@extends('layouts.master')
@section('page_title', 'Accounts Dashboard')
@section('content')
<div class="d-flex justify-content-between align-items-center mb-3"><div><h2 class="mb-1">Accounts dashboard</h2><p class="text-muted mb-0">Fee collection overview for {{ $session }}</p></div><a href="{{ route('payments.manage') }}" class="btn btn-primary"><i class="icon-coins mr-1"></i>Manage student payments</a></div>
<div class="row">
    @foreach([['Invoiced', $invoiced, 'icon-file-text2', 'bg-primary-400'], ['Collected', $collected, 'icon-checkmark3', 'bg-success-400'], ['Outstanding', $outstanding, 'icon-warning22', 'bg-danger-400'], ['Fee items', $payments->count(), 'icon-list-unordered', 'bg-indigo-400']] as $metric)
        <div class="col-sm-6 col-xl-3"><div class="card card-body {{ $metric[3] }} has-bg-image"><div class="media"><div class="media-body"><h3 class="mb-0">{{ is_numeric($metric[1]) && $metric[0] !== 'Fee items' ? number_format($metric[1], 2) : $metric[1] }}</h3><span class="text-uppercase font-size-xs font-weight-bold">{{ $metric[0] }}</span></div><i class="{{ $metric[2] }} icon-3x opacity-75"></i></div></div></div>
    @endforeach
</div>
<div class="row"><div class="col-lg-8"><div class="card"><div class="card-header header-elements-inline"><h5 class="card-title">Fee items this session</h5>{!! Qs::getPanelOptions() !!}</div><div class="table-responsive"><table class="table table-hover mb-0"><thead><tr><th>Fee item</th><th>Amount</th><th>Class</th><th>Reference</th></tr></thead><tbody>@forelse($payments as $payment)<tr><td>{{ $payment->title }}</td><td>{{ number_format($payment->amount, 2) }}</td><td>{{ optional($payment->my_class)->name ?: 'All classes' }}</td><td>{{ $payment->ref_no }}</td></tr>@empty<tr><td colspan="4" class="text-center text-muted">No fee items configured for this session.</td></tr>@endforelse</tbody></table></div></div></div><div class="col-lg-4"><div class="card card-body"><h5>Collection progress</h5><div class="progress mb-2" style="height:10px"><div class="progress-bar bg-success" style="width: {{ $invoiced > 0 ? min(100, ($collected / $invoiced) * 100) : 0 }}%"></div></div><p class="mb-0 text-muted">{{ $invoiced > 0 ? number_format(($collected / $invoiced) * 100, 1) : 0 }}% of invoiced fees collected.</p></div><div class="card"><div class="card-header"><h5 class="card-title">Quick links</h5></div><div class="list-group list-group-flush"><a class="list-group-item list-group-item-action" href="{{ route('payments.create') }}">Create fee item</a><a class="list-group-item list-group-item-action" href="{{ route('payments.index') }}">Fee history</a></div></div></div></div>
@endsection
